---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by HP.
--- DateTime: 2024/11/5 15:35
---
local rawKey = KEYS[1] ---- item-service:items_purchase_stock_bucket
local itemIdPrefixLen = 4

local jsonArrayStr = ARGV[1]
local jsonArray = cjson.decode(jsonArrayStr)

for idx,jsonObj in ipairs(jsonArray) do
    local itemIdStr = tostring(jsonObj.itemId)
    local amount = tonumber(jsonObj.amount)
    if itemIdStr == nil or amount == nil or amount < 0 then
        return "fail-16"
    end
    local itemIdPrefix = string.sub(itemIdStr,-itemIdPrefixLen,-1);
    if itemIdPrefix == nil or #itemIdPrefix ~= itemIdPrefixLen then
        return "fail-21"
    end
    local actualKey = rawKey .. ":" .. itemIdPrefix .. ":" .. itemIdStr
    local innerKey = "stock"
    --local stock = tonumber(redis.call("HGET", actualKey, innerKey))
    --if stock == nil then
    --    return "fail-26 " .."/stock = " ..tostring(stock) .."/actualKey=".. tostring(actualKey) .."/innerKey=" .. innerKey
    --end
    redis.call('hincrby', actualKey, innerKey, amount)
end

return "success"
